apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
spec:
  capacity:
    storage: 300m
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-nginx
# spec:
#   resources:
#     requests:
#       storage: <Size>
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce

